spring.config.import=optional:file:.env[.properties]
spring.application.name=Intern
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
# Disable SQL logs
logging.level.org.springframework=ERROR
logging.level.org.springframework.amqp=ERROR
logging.level.com.rabbitmq=ERROR
# Turn off Hibernate SQL logging
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.root=INFO

# Silence noisy frameworks
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.org.apache.tomcat=ERROR